# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: 'Default'
  demands: []

jobs:
- job: BuildAndTest
  displayName: 'Build and Test Job'
  steps:
  - script: echo Hello, world!
    displayName: 'Echo Hello World'

  - task: Maven@4
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean install'
    displayName: 'Run Maven Clean Install'
